# version: "3.9"

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  bot:
    build: .
    command: python bot.py
    volumes:
      - .:/app
    depends_on:
      - web
