# Generated by Django 5.2.5 on 2025-08-31 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=512, null=True)),
                ('first_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('message_text', models.TextField()),
                ('contains_keyword', models.BooleanField(default=False)),
                ('matched_keywords', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='monitor.monitoredgroup')),
            ],
        ),
        migrations.CreateModel(
            name='RentalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=512, null=True)),
                ('first_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('last_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_id', models.BigIntegerField()),
                ('photos', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('audio_files', models.JSONField(blank=True, default=list)),
                ('voice_messages', models.JSONField(blank=True, default=list)),
                ('rental_keywords_found', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('raw_telegram_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_announcements', to='monitor.monitoredgroup')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'created_at'], name='monitor_ren_group_i_2a07a6_idx'), models.Index(fields=['user_id'], name='monitor_ren_user_id_5046cd_idx'), models.Index(fields=['is_processed'], name='monitor_ren_is_proc_909031_idx'), models.Index(fields=['confidence_score'], name='monitor_ren_confide_d5796a_idx')],
            },
        ),
    ]
