# Generated by Django 5.2.5 on 2025-08-31 10:45

import django.db.models.deletion
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=512, null=True)),
                ('first_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('message_text', models.TextField()),
                ('contains_keyword', models.BooleanField(default=False)),
                ('matched_keywords', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='monitor.monitoredgroup')),
            ],
        ),
        migrations.CreateModel(
            name='RentalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=512, null=True)),
                ('first_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('last_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_id', models.BigIntegerField()),
                ('photos_data', models.JSONField(blank=True, default=list)),
                ('videos_data', models.JSONField(blank=True, default=list)),
                ('documents_data', models.JSONField(blank=True, default=list)),
                ('audio_files_data', models.JSONField(blank=True, default=list)),
                ('voice_messages_data', models.JSONField(blank=True, default=list)),
                ('rental_keywords_found', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('raw_telegram_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_announcements', to='monitor.monitoredgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('voice', 'Voice Message'), ('video_note', 'Video Note')], max_length=20)),
                ('file_id', models.CharField(max_length=512)),
                ('file_unique_id', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=256, null=True)),
                ('file_name', models.CharField(blank=True, max_length=512, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('local_file', models.FileField(blank=True, null=True, upload_to=monitor.models.rental_media_upload_path)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('telegram_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('download_error', models.TextField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='monitor.rentalannouncement')),
            ],
        ),
        migrations.AddIndex(
            model_name='rentalannouncement',
            index=models.Index(fields=['group', 'created_at'], name='monitor_ren_group_i_2a07a6_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalannouncement',
            index=models.Index(fields=['user_id'], name='monitor_ren_user_id_5046cd_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalannouncement',
            index=models.Index(fields=['is_processed'], name='monitor_ren_is_proc_909031_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalannouncement',
            index=models.Index(fields=['confidence_score'], name='monitor_ren_confide_d5796a_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalmediafile',
            index=models.Index(fields=['announcement', 'media_type'], name='monitor_ren_announc_b670a8_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalmediafile',
            index=models.Index(fields=['file_id'], name='monitor_ren_file_id_f50c62_idx'),
        ),
    ]
