# Generated by Django 5.2.5 on 2025-08-31 09:42

import django.db.models.deletion
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalannouncement',
            old_name='audio_files',
            new_name='audio_files_data',
        ),
        migrations.RenameField(
            model_name='rentalannouncement',
            old_name='documents',
            new_name='documents_data',
        ),
        migrations.RenameField(
            model_name='rentalannouncement',
            old_name='photos',
            new_name='photos_data',
        ),
        migrations.RenameField(
            model_name='rentalannouncement',
            old_name='videos',
            new_name='videos_data',
        ),
        migrations.RenameField(
            model_name='rentalannouncement',
            old_name='voice_messages',
            new_name='voice_messages_data',
        ),
        migrations.CreateModel(
            name='RentalMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('voice', 'Voice Message'), ('video_note', 'Video Note')], max_length=20)),
                ('file_id', models.CharField(max_length=512)),
                ('file_unique_id', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=256, null=True)),
                ('file_name', models.CharField(blank=True, max_length=512, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('local_file', models.FileField(blank=True, null=True, upload_to=monitor.models.rental_media_upload_path)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('telegram_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('download_error', models.TextField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='monitor.rentalannouncement')),
            ],
            options={
                'indexes': [models.Index(fields=['announcement', 'media_type'], name='monitor_ren_announc_b670a8_idx'), models.Index(fields=['file_id'], name='monitor_ren_file_id_f50c62_idx')],
            },
        ),
    ]
